name: Generate Profile Orbit

on:
  schedule:
    # Ejecuta automáticamente todos los días a medianoche (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutar manualmente desde la pestaña Actions de GitHub
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-orbit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Cosmos Visualization
        uses: NiconiKimg/github-profile-orbit@v1
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          template: space
          theme: auto
          role: Developer
          output_path: dist/github-cosmos.svg
          include_forks: false
          include_archived: false
          max_repositories: 30
          exclude_repositories: |
            TPA-TPIntegrador
          external_repositories: |
            SIGMA-LA/Front-End-SIGMA-LA
            SIGMA-LA/Back-End-SIGMA-LA
            upskill-team/Front-End-DSW
            upskill-team/Back-End-DSW
            carlex74/TP-FINAL-.NET
            LucaTvl/Hyperparameters-Optimization
            LucaTvl/CIFAR-Playground
            NiconiKimg/AnyLogicWebToolkit
            upskill-team/propuesta-DSW
          auto_commit: true
          commit_message: "chore(orbit): update visualization [skip ci]"
